const USER = '/user';
const LOGIN = '/login';
const LOGOUT  = '/logout';
const POST = '/post';
const GROUPMEMBERS = '/groupmembers';
const GROUP = '/group';
const FRIEND = '/friend';
const COMMENT = '/comment';
const USERPASSWD = '/userpassword';
const POSTGROUP = '/postgroup';
const MYPOSTS = '/myposts';
const UPLOAD = '/upload';
const FRIENDGROUPS = '/friendgroups';
const REJECTFRIEND = '/rejectfriend';
const ADMINUSERS = '/adminusers';
const ADMINSTATUS = '/adminstatus';
const REACTION = '/reaction';

module.exports={REACTION, ADMINSTATUS, ADMINUSERS, REJECTFRIEND, FRIENDGROUPS, UPLOAD, MYPOSTS, USER, USERPASSWD, LOGIN, LOGOUT, POST, GROUPMEMBERS, GROUP, FRIEND, COMMENT, POSTGROUP};