
###

POST http://cpsc.roanoke.edu:3009/login
content-type: application/json


{"user_email": "catsarisky@gmail.com",
"password": "gottagetanewpwd"}

###


POST http://cpsc.roanoke.edu:3009/userpassword
content-type: application/json
cookie: sessionid=2e284cda-2a76-49ee-a8ec-67861df05028

{"user_email": "catsarisky@gmail.com",
"newpassword": "gottagetanewpwd"}

###

PUT http://cpsc.roanoke.edu:3009/user
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{
"user_email": "catsarisky@gmail.com",
"user_handle": "catsari's new handle"
}
###
GET http://cpsc.roanoke.edu:3009/user
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
###


GET http://cpsc.roanoke.edu:3009/user?search=young
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
###

GET http://cpsc.roanoke.edu:3009/groupmembers?group_id=2
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54
###

POST http://cpsc.roanoke.edu:3009/groupmembers
content-type: application/json
cookie: sessionid=076fe3b2-bc21-4116-9ee4-4c418f19e733

{"group_id": 10, "friend_id": 13}

###
DELETE http://cpsc.roanoke.edu:3009/groupmembers?group_id=10&friend_id=11
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
### 


GET http://cpsc.roanoke.edu:3009/myposts
content-type: application/json
cookie: sessionid=6d6419bc-03aa-495b-8edd-c47602e45077
###

GET http://cpsc.roanoke.edu:3009/post
content-type: application/json
cookie: sessionid=6d6419bc-03aa-495b-8edd-c47602e45077
###

POST http://cpsc.roanoke.edu:3009/post
content-type: application/json
cookie: sessionid=f0969177-914e-4884-b7ae-b844c10e8993

{"post_title": "This is a super awesome post", "post_content": "Lorem ipsum forever", "group_id": "10,2" }
###

GET http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
###

POST http://cpsc.roanoke.edu:3009/friend
content-type: application/json
cookie: sessionid=fbb1b3b9-7c5c-43cf-a5c7-3ace0913df30

{"friend_id": 8}

###
GET http://cpsc.roanoke.edu:3009/friend?status_wanted=requested
content-type: application/json
cookie: sessionid=fbb1b3b9-7c5c-43cf-a5c7-3ace0913df30

###
GET http://cpsc.roanoke.edu:3009/friend
content-type: application/json
cookie: sessionid=fbb1b3b9-7c5c-43cf-a5c7-3ace0913df30

###
POST http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"group_name": "Tired coders", "group_ranking": 3}

###


PUT http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"group_id": 5, "group_ranking": 5}

###
POST http://cpsc.roanoke.edu:3009/comment
content-type: application/json
cookie: sessionid=6d6419bc-03aa-495b-8edd-c47602e45077

{"post_id": 5, "comment_content": "commenting on my own post, too!!!"}

###


POST http://cpsc.roanoke.edu:3009/postgroup
content-type: application/json
cookie: sessionid=f0969177-914e-4884-b7ae-b844c10e8993

{"post_id": 7, "group_id": 10}

###

DELETE http://cpsc.roanoke.edu:3009/postgroup?post_id=7&group_id=10
content-type: application/json
cookie: sessionid=f0969177-914e-4884-b7ae-b844c10e8993


###
GET http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54
###


GET http://cpsc.roanoke.edu:3009/friendgroups?friend_id=2
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54
###

GET http://cpsc.roanoke.edu:3009/comment?post_id=1
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

### 

select * from 
(select 1 as result, group_id from group_memberships where user_id=2 and group_id in (select group_id from groups where owner_id=1))
full join on groups using group_id

select group_id from group_memberships where user_id=2 and group_id in (select group_id from groups where owner_id=1) ;

select group_name, group_id, user_id from (
    (
    select group_id, user_id from group_memberships where user_id=2 
        AND group_id in (select group_id from groups where owner_id=1)
    ) a 
    cross join groups using (group_id)  
) b 
where b.owner_id=1;



    select group_id, user_id from group_memberships gm 
    
    cross join groups using (group_id)  
    where gm.user_id=2 
        AND gm.group_id in (select group_id from groups where owner_id=1)

select group_id, group_name, user_id from group_memberships right join groups using (group_id) 
    where group_id in (select group_id from groups where owner_id=1)

select group_id, group_name, user_id from (select group_id, user_id from group_memberships where user_id=2) b right join groups using (group_id) 
    where group_id in (select group_id from groups where owner_id=1);
