
###

POST http://cpsc.roanoke.edu:3009/login
content-type: application/json


{"user_email": "catsarisky@gmail.com",
"password": "gottagetanewpwd"}

###


POST http://cpsc.roanoke.edu:3009/userpassword
content-type: application/json
cookie: sessionid=2e284cda-2a76-49ee-a8ec-67861df05028

{"user_email": "catsarisky@gmail.com",
"newpassword": "gottagetanewpwd"}

###

GET http://cpsc.roanoke.edu:3009/user
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
###


GET http://cpsc.roanoke.edu:3009/user?search=young
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
###

GET http://cpsc.roanoke.edu:3009/groupmembers?group_id=2
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

###
DELETE http://cpsc.roanoke.edu:3009/groupmembers?group_id=2&friend_id=2
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
### 

GET http://cpsc.roanoke.edu:3009/post
content-type: application/json
cookie: sessionid=f0969177-914e-4884-b7ae-b844c10e8993
###

POST http://cpsc.roanoke.edu:3009/post
content-type: application/json
cookie: sessionid=f0969177-914e-4884-b7ae-b844c10e8993

{"post_title": "nother post 4", "post_content": "Lorem ipsum forever", "group_id": 10}
###

GET http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
###

GET http://cpsc.roanoke.edu:3009/friend
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301

###

POST http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"group_name": "Tired coders", "group_ranking": 3}

###


PUT http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"group_id": 5, "group_ranking": 5}

###
POST http://cpsc.roanoke.edu:3009/comment
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"post_id": 1, "comment_content": "making still more comments!!"}

###


POST http://cpsc.roanoke.edu:3009/postgroup
content-type: application/json
cookie: sessionid=f0969177-914e-4884-b7ae-b844c10e8993

{"post_id": 7, "group_id": 10}

###

DELETE http://cpsc.roanoke.edu:3009/postgroup?post_id=7&group_id=10
content-type: application/json
cookie: sessionid=f0969177-914e-4884-b7ae-b844c10e8993


###
GET http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54
###

GET http://cpsc.roanoke.edu:3009/comment?post_id=1
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

### 
