
###

POST http://cpsc.roanoke.edu:3009/login
content-type: application/json

{"user_email": "catsarisky@gmail.com",
"password": "gottagetapwd"}

###

GET http://cpsc.roanoke.edu:3009/user
content-type: application/json
cookie: sessionid=2026fadb-68f5-48af-aaeb-ad1e60c79301
###


GET http://cpsc.roanoke.edu:3009/groupmembers
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"group_id": "1"}

### 

GET http://cpsc.roanoke.edu:3009/post
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54
###

GET http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54
###

GET http://cpsc.roanoke.edu:3009/friend
content-type: application/json
cookie: sessionid=ec9256a8-d844-493c-9a6b-527977ef6be8

###

POST http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"group_name": "Silly noodles", "group_ranking": 3}

###


PUT http://cpsc.roanoke.edu:3009/group
content-type: application/json
cookie: sessionid=c94b1d7e-f11d-4673-b774-7d76746dac54

{"group_id": 1, "group_ranking": 1}

###